### ISSUE TITLE
Gnome 45 compatibilty please

### ISSUE THREAD

**Issue by Spinnekop** [Isopolito/gNordVPN-Local#73]
Self explanatory!!

**Comment by Isopolito** [comment]
Hi @Spinnekop, once I test and confirm that it works on gnome 45 I'll release the extension for that version. Should be soon. Thanks for the feedback

**Comment by Isopolito** [comment]
Just an update--this work is mostly done. There's a bug that's preventing the prefs dialog from opening up. Once that's resolved I'll submit a new version of the extension for review. 

This is the [branch](https://github.com/Isopolito/gNordVPN-Local/tree/Gnome45) I'm working out of if you want to test drive things. The feedback would be welcome. Cheers

**Comment by tdtooke** [comment]
Thanks!!  It works again.  I'm definitely eagerly waiting for prefs to work again because I always have to toy with the css to make it look right on my shell.

**Comment by tdtooke** [comment]
I just checked out your latest release with preferences working and everything is fine except for one small thing.  Gnome freezes on boot if I have the extension enabled.  I can however start it without it enabled and then enable it after I'm in Gnome.

**Comment by Isopolito** [comment]
Hi @Spinnekop and @tdtooke, I'm trying to replicate this freeze. What distros are you all using? Can you run this and post the output?

` dconf dump /org/gnome/shell/extensions/gnordvpn-local/`

@Spinnekop Is there anything in particular you do that causes a freeze?

**Comment by Spinnekop** [comment]
dconf dump /org/gnome/shell/extensions/gnordvpn-local/  shows nothing
libsoup 2.74.3-1
libsoup3 3.4.4-1
Using Arch btw. Freezes immediately after entering password in gdm

**Comment by tdtooke** [comment]
I experimented a little bit and found that there is no problem if you use sddm but then you have to figure out another way to have screen locking.  Also if you use gdm and boot plasma first, then log out, then log into gnome it'll work. (I have kde and gnome)

**Comment by tdtooke** [comment]
Forget that last part, I deleted that other extension and that went away.

**Comment by Isopolito** [comment]
Thanks for the feedback @tdtooke and @Spinnekop. When you look at the logs, any gnordvpn-local specific entries will have either "gnord" somewhere in the message or will have a file name in the stack trace with "gnordvpn" in it.

**Comment by tdtooke** [comment]
Running GNOME Shell (using mutter 45.1) as a Wayland display server
Failed to make thread 'KMS thread' realtime scheduled: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.RealtimeKit1" does not exist
Device '/dev/dri/card1' prefers shadow buffer
Added device '/dev/dri/card1' (i915) using atomic mode setting.
Created gbm renderer for '/dev/dri/card1'
Boot VGA GPU /dev/dri/card1 selected as primary
Obtained a high priority EGL context
Obtained a high priority EGL context
Using public X11 display :1024, (using :1025 for managed services)
Using Wayland display name 'wayland-0'
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 1
Extension light-style@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/light-style@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/light-style@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension pamac-updates@manjaro.org already installed in /usr/share/gnome-shell/extensions/pamac-updates@manjaro.org. /usr/share/gnome-shell/extensions/pamac-updates@manjaro.org will not be loaded
Extension blur-my-shell@aunetx already installed in /usr/share/gnome-shell/extensions/blur-my-shell@aunetx. /usr/share/gnome-shell/extensions/blur-my-shell@aunetx will not be loaded
Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension auto-move-windows@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/auto-move-windows@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/auto-move-windows@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension drive-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension native-window-placement@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/native-window-placement@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/native-window-placement@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension windowsNavigator@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/windowsNavigator@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/windowsNavigator@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension workspace-indicator@gnome-shell-extensions.gcampax.github.com already installed in /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com will not be loaded
Window manager warning: Failed to parse saved session file: Failed to open file “/var/lib/gdm/.config/mutter/sessions/10744d4361ebe20a19169982182195788200000007960000.ms”: No such file or directory
Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Ignoring length property that isn't a number at line 5388, col 24
Ignoring length property that isn't a number at line 5388, col 24
Ignoring length property that isn't a number at line 5388, col 24
Registering session with GDM
Connection to xwayland lost
Xwayland terminated, exiting since it was mandatory
JS ERROR: Gio.IOErrorEnum: Xwayland exited unexpectedly
@resource:///org/gnome/shell/ui/init.js:21:20

Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception

is the output for clear; journalctl -f -e -o cat /usr/bin/gnome-shell

**Comment by Spinnekop** [comment]
Sorry - I am using the terminal for this now....

**Comment by goldentg** [comment]
is this project still being maintained?

**Comment by Isopolito** [comment]
Hi @goldentg, 

Yeah, I'm partially done with the work, it's in the gnome45 branch. I got pulled away for a while but plan on jumping back on it asap. The main issue is in the VPN module, async calls are freezing up.

Feel free to give it a crack if you know JavaScript

**Comment by Isopolito** [comment]
@Spinnekop  and @tdtooke and @sksavant gnome 45 version of this extension has been released
