### ISSUE TITLE
No Country/City/Server in popup menu

### ISSUE THREAD

**Issue by Spinnekop** [Isopolito/gNordVPN-Local#87]
Gnome 45 on Arch.  No country in settings menu either. Countries list is blank in Cities and Server settings

**Comment by Isopolito** [comment]
Hi,

Thanks for putting this on my radar. I'll take a look next opportunity I have to work on this extension.

**Comment by Isopolito** [comment]
So I just upgraded for the first time in a while and now I have the same issue. Something must have changed, I'll try to get to this as soon as possible. Feel free to dig and send a PR

**Comment by Isopolito** [comment]
@Spinnekop, NordVPN changed some formatting of the output that broke the countries/city logic. Fixed, submitted changes for review. Thanks for the feedback

**Comment by xarpy** [comment]
Hi Isopolito,  sorry to open again the issue, but for anothers version on gnome, the same problem still happening. Take a look the prints from my system. I just use Ubuntu 22.04 with gnome 42.9, can you help to solve this problem?
![image](https://github.com/Isopolito/gNordVPN-Local/assets/46647557/30b77311-5d93-4d91-b4d4-078505dfb2df)

**Comment by Isopolito** [comment]
Hi @xarpy,

So I think the issue is that you're on an old version of the extension, but likely using a newer version of the nordvpn cli. So the newer format of the CLI output is not able to be handled by the older extension code you're running.

Any reason you can't upgrade the latest stable on gnome?

BTW nice background!
