### ISSUE TITLE
Critical Problem with Ubuntu 24.04 and Nordvpn 3.17.4

### ISSUE THREAD

**Issue by kevinmarchant** [Isopolito/gNordVPN-Local#92]
**Describe the bug**
I’ve done a clean install of Ubuntu 24.04 and used the NordVPN install script to install.  Then added gNordVPN-local from extensions.gnome.org.  I don't connect via the extension - I use either autoconnect or the NordVPN CLI.

NordVPN does work and status displayed by gNordVPN for the session but critical  NordVPN settings are being LOST over a reboot.

Errors appear for any NordVPN cli commands in /home/$USER/.config/nordvpn (a directory which I believe deprecated from a nordvpn point of view as settings are now stored in /var/lib/nordvpn)

The following NordVPN settings are changed every reboot

- Technology - defaults back to OpenVPN after a reboot
- Firewall - resets to Off after a reboot
- Notify - resets to Off after a reboot
- Auto-connect - resets of Off after a reboot.

Whilst others are retained:

- DNS
- Allowlisted subnets

I’ve completely uninstalled (apt remove /apt purge and deleted /var/lib/nordvpn, /var/run/nordvpn, /home/$USER/.config/nordvpn) and reinstalled a couple of times.  But after disabling gNordVPN-local NordVPN starts working as expected.

Errors are appearing in /home/$USER/.config/nordvpn/cli..log for every nordvpn cli command issued.

2024/05/01 14:37:46 [Error] stty: 'standard input': Inappropriate ioctl for device
2024/05/01 15:13:01 [Error] stty: 'standard input': Inappropriate ioctl for device
2024/05/01 15:13:02 Something went wrong. Please try again. If the problem persists, contact our customer support.

On disabling gNordVPN-local the errors stop.

To reproduce,  
nordvpn set technology nordlynx
nordvpn settings --> shows technology set to nordlynx
sudo reboot
nordvpn settings --> shows technology reset to openvpn
|

**Comment by Isopolito** [comment]
Hi,

It's possible the errors you're seeing are from gnordvpn trying to apply settings that are invalid based on the technology selected. if that's the case, some logic could be added to apply only the settings that make sense based on the selected tech.  If you are familiar with JS, feel free to dive in and create a PR. 

As far as things getting reset on reboot, if I understand the issue correctly, it's possible that you're setting things in CLI, but it's set differently in the gnordvpn settings. On enable, gnordvpn will apply whatever settings you have configured via the UI to nordvpn in order to sync it up with your gnordvpn configuration.

**Comment by kevinmarchant** [comment]
Hi Austin

Apologies.  Even though I've used your extension for a while I don't think I've ever explored how you are supposed to use it and what it did.

I've only ever used it as a passive display of VPN connection status and hadn't realised that technology, firewall and autoconnect were settings were defined in the extension and were applied at every reboot.  So configuring those options in the extension gives me the desired effect.

I still can't configure "Notify" - it's disabled by the extension and there doesn't appear to be an option to enable it - but as that's the whole point of the extension in the first place I guess this comment is mute.

Still getting errors in /home/$USER/.config/nordvpn 
2024/05/02 15:17:53 [Error] stty: 'standard input': Inappropriate ioctl for device

I'll see if I configure out if it is something in my config though the only other settings I've configured are DNS and two Allowlist subnets.

Once again apologies for thinking somethings was broken when in fact it's a combination of user-incompetence and a couple of minor observations.

Kevin

**Comment by Isopolito** [comment]
Hi @kevinmarchant, your points are valid. I've tried to make it so that UI will disable/enable flags based based on what's allowed with the current state of the configuration, but there's probably room for improvement there.

 Also, Notify wasn't available via the Linux CLI at the time I was working on that stuff, so I didn't add that in. I should revisit that now though.

To your point of gnordvpn overriding the CLI. That could actually be configurable via a toggle on the general settings page. You could set which side is the source of truth for configuration.

If you know JS or want to learn feel free to jump on any or all of those. Contributions are always very welcome

Cheers
